### ISSUE TITLE
New import immediately fails with page build error on gh-pages

### ISSUE THREAD

**Issue by wdconinc** [hsf-training/hsf-styles#6]
## Steps to reproduce:
1. Import new repository at https://github.com/new/import
2. Old repository = https://github.com/hsf-training/hsf-styles
3. Wait for email confirming creation...

(Links below refer to https://github.com/hsf-training/hsf-training-spack-webpage.)

## Expected outcomes:
Pages should build correctly and appear at https://hsf-training.github.io/hsf-training-spack-webpage/.

## Actual outcomes:
Email with failure arrives, also visible in Settings > [Pages](https://github.com/hsf-training/hsf-training-spack-webpage/settings/pages). No page is built at e.g. https://hsf-training.github.io/hsf-training-spack-webpage/.
> The page build failed for the `gh-pages` branch with the following error:
> 
> Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request at https://support.github.com/contact?tags=dotcom-pages&repo_id=463218858&page_build_id=319151582
> 

## Possible causes:
Quick review with local bundler exec jekyll serve indicates:
> jekyll 3.9.0 | Error:  Could not find document 'index.md' in tag 'link'.

But maybe there is no expectation of this working correctly until a first lesson is created, and we should add this to https://hepsoftwarefoundation.org/training/howto-new-module.html.

**Comment by wdconinc** [comment]
This is indeed resolved by the next step `python3 bin/lesson_initialize.py`. Still might be nice to avoid the first build error with a simple minimal index.md as part of the style, if technically possible.

**Comment by klieret** [comment]
Hi @wdconinc Sorry for not coming back to this earlier. Thanks for writing this up!

I don't think this was previously possible because of the way this was being synced.

Since we will now probably soon fully switch to using the Jekyll theme and syncing the few other files differently, this is probably solved/no longer relevant.
