### ISSUE TITLE
godbolt support for code block

### ISSUE THREAD

**Issue by wdconinc** [hsf-training/hsf-styles#7]
I wonder if it would be possible to support godbolt iframes for c++ syntax like ([link](https://godbolt.org/#g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:4,positionColumn:2,positionLineNumber:4,selectionStartColumn:2,selectionStartLineNumber:4,startColumn:2,startLineNumber:4),source:'//+Type+your+code+here,+or+load+an+example.%0Aint+square(int+num)+%7B%0A++++return+num+*+num%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:100,l:'4',m:100,n:'0',o:'',s:0,t:'0')),version:4))
~~~
```godbolt
int square(int num) {
    return num * num;
}
```
~~~
to end up with an embedded godbolt iframe, e.g. replacing this with
```
<iframe width="800px" height="200px" src="https://gcc.godbolt.org/e#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:31,endLineNumber:5,positionColumn:31,positionLineNumber:5,selectionStartColumn:31,selectionStartLineNumber:5,startColumn:31,startLineNumber:5),source:'//+Using+lambdas+is+very+cheap!!+And+you+can%0A//+define+and+use+a+lambda+inline+in+a+single%0A//+statement!!%0Aint+main()+%7B%0A++return+%5B%5D()+%7B+return+5%3B+%7D()%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:g112,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+gcc+11.2+(C%2B%2B,+Editor+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4"></iframe>
```
and ending up with an embedded segment like this (screenshot):
![image](https://user-images.githubusercontent.com/4656391/157100455-430b6e82-3836-4431-bce6-e88cb9140447.png)

The goal would be to easily integrate interactive components into tutorials.

This would allow for some really powerful constructs for c++ courses...

**Comment by klieret** [comment]
You can always directly include HTML in the markdown files, so you can already include it.

However, for the convenient markdown syntax, you'd probably have to write a Ruby preprocessor to search and replace it. It's probably not too hard, though.

Are you planning on using this extensively? Else I'd say that being able to include it as HTML in some places is good enough for now, and we will reopen this if we have someone working on this.

**Comment by wdconinc** [comment]
I think it doesn't fit with the philosophy of carpentry-style courses: having in-browser evaluation leads to an overly confident learner who does not have to copy the code into a different as a a minimal learning step. For that reason, I think this is probably not recommended (even if technically possible).

**Comment by klieret** [comment]
Yeah, that might be true. I'm closing this then :)
